# Generated by Django 4.2 on 2025-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptiton',
            new_name='description',
        ),
    ]
